### ISSUE TITLE
TweetListener got bad status code: 420

### ISSUE THREAD

**Issue by khangaikh** [propublica/politwoops-tweet-collector#12]
It am testing and it was working properly before but now twitter keep giving me 420. Any suggestions

**Comment by timball** [comment]
> 420 Enhance Your Calm (Twitter <http://en.m.wikipedia.org/wiki/Twitter>)Not
part of the HTTP standard, but returned by version 1 of the Twitter Search
and Trends API when the client is being rate limited.[17]
<http://en.m.wikipedia.org/wiki/List_of_HTTP_status_codes#cite_note-TwitterErrorCodes-18>
Other
services may wish to implement the 429 Too Many Requests
<http://en.m.wikipedia.org/wiki/List_of_HTTP_status_codes#429> response
code instead.

slow your roll . you probably have a list way too big and are making way
too many requests .

--timball
