### ISSUE TITLE
Open to enhancements?

### ISSUE THREAD

**Issue by nowfred** [propublica/politwoops-tweet-collector#14]
Hey, this looks like a neat tool!

Is this something you are actively using? Let me know, would love to do some work on this, like testing and/or dockerization 

Thanks!

**Comment by dwillis** [comment]
@nowfred Thanks! We just inherited it from the Sunlight Foundation and we definitely use it in Politwoops, which we're switching to a Dockerized app. Would welcome any testing or other contributions.

**Comment by nowfred** [comment]
@dwillis Great! 

Another question - if you are switching politwhoops to be a dockerized app, would it not be a good use of my time to convert this repo to have a `docker-compose up` behavior? I have experience with this and python applications but if you have begun elsewhere I will not tread on toes.
